name: testing

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          components: clippy

      - name: "Test example server"
        run: |
          cargo run -- --verbose server init -m 1.20.4 -l fabric
          cargo run -- --verbose project add simple-voice-chat -o

          mkdir another-server && cd another-server
          cp ../pap.lock .
          cargo run -- --verbose server install
